// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Disease struct {
	DiseaseID   int    `json:"diseaseID"`
	DiseaseName string `json:"diseaseName"`
}

type DiseaseInput struct {
	DiseaseName string `json:"diseaseName"`
}

type Medicament struct {
	ID                                                   string `json:"id"`
	Numero                                               string `json:"numero"`
	NumeroEnregistrement                                 string `json:"numeroEnregistrement"`
	Code                                                 string `json:"code"`
	DenominationCommuneInternationale                    string `json:"denominationCommuneInternationale"`
	NomDeMarque                                          string `json:"nomDeMarque"`
	Forme                                                string `json:"forme"`
	Dosage                                               string `json:"dosage"`
	Cond                                                 string `json:"cond"`
	Liste                                                string `json:"liste"`
	P1                                                   string `json:"p1"`
	P2                                                   string `json:"p2"`
	Obs                                                  string `json:"obs"`
	LaboratoiresDetenteurDeLaDecisionEnregistrement      string `json:"laboratoiresDetenteurDeLaDecisionEnregistrement"`
	PaysDuLaboratoireDetenteurDeLaDecisionEnregistrement string `json:"paysDuLaboratoireDetenteurDeLaDecisionEnregistrement"`
	DateEnregistrementInitial                            string `json:"dateEnregistrementInitial"`
	DateEnregistrementFinal                              string `json:"dateEnregistrementFinal"`
	Type                                                 string `json:"type"`
	Statut                                               string `json:"statut"`
	DureeDeStabilite                                     string `json:"dureeDeStabilite"`
}

type MedicamentInput struct {
	Numero                                               *string `json:"numero,omitempty"`
	NumeroEnregistrement                                 *string `json:"numeroEnregistrement,omitempty"`
	Code                                                 *string `json:"code,omitempty"`
	DenominationCommuneInternationale                    *string `json:"denominationCommuneInternationale,omitempty"`
	NomDeMarque                                          *string `json:"nomDeMarque,omitempty"`
	Forme                                                *string `json:"forme,omitempty"`
	Dosage                                               *string `json:"dosage,omitempty"`
	Cond                                                 *string `json:"cond,omitempty"`
	Liste                                                *string `json:"liste,omitempty"`
	P1                                                   *string `json:"p1,omitempty"`
	P2                                                   *string `json:"p2,omitempty"`
	Obs                                                  *string `json:"obs,omitempty"`
	LaboratoiresDetenteurDeLaDecisionEnregistrement      *string `json:"laboratoiresDetenteurDeLaDecisionEnregistrement,omitempty"`
	PaysDuLaboratoireDetenteurDeLaDecisionEnregistrement *string `json:"paysDuLaboratoireDetenteurDeLaDecisionEnregistrement,omitempty"`
	DateEnregistrementInitial                            *string `json:"dateEnregistrementInitial,omitempty"`
	DateEnregistrementFinal                              *string `json:"dateEnregistrementFinal,omitempty"`
	Type                                                 *string `json:"type,omitempty"`
	Statut                                               *string `json:"statut,omitempty"`
	DureeDeStabilite                                     *string `json:"dureeDeStabilite,omitempty"`
}

type Mutation struct {
}

type Patient struct {
	PatientID             int     `json:"patientID"`
	Notes                 *string `json:"notes,omitempty"`
	BloodType             *string `json:"bloodType,omitempty"`
	EmergencyContactName  *string `json:"emergencyContactName,omitempty"`
	EmergencyContactPhone *string `json:"emergencyContactPhone,omitempty"`
	InsuranceProvider     *string `json:"insuranceProvider,omitempty"`
	InsurancePolicyNumber *string `json:"insurancePolicyNumber,omitempty"`
	CreatedAt             int     `json:"createdAt"`
	UpdatedAt             int     `json:"updatedAt"`
	FirstName             string  `json:"firstName"`
	LastName              string  `json:"lastName"`
	Email                 *string `json:"email,omitempty"`
	PhoneNumber           string  `json:"phoneNumber"`
	Address               *string `json:"address,omitempty"`
	DateOfBirth           int     `json:"dateOfBirth"`
	Gender                string  `json:"gender"`
	Status                string  `json:"status"`
	ProfilePicture        *string `json:"profilePicture,omitempty"`
}

type PatientDisease struct {
	PatientID int `json:"patientID"`
	DiseaseID int `json:"diseaseID"`
}

type PatientDiseaseInput struct {
	PatientID int `json:"patientID"`
	DiseaseID int `json:"diseaseID"`
}

type PatientInput struct {
	Notes                 *string `json:"notes,omitempty"`
	BloodType             string  `json:"bloodType"`
	EmergencyContactName  *string `json:"emergencyContactName,omitempty"`
	EmergencyContactPhone *string `json:"emergencyContactPhone,omitempty"`
	InsuranceProvider     *string `json:"insuranceProvider,omitempty"`
	InsurancePolicyNumber *string `json:"insurancePolicyNumber,omitempty"`
	FirstName             string  `json:"firstName"`
	LastName              string  `json:"lastName"`
	Email                 *string `json:"email,omitempty"`
	PhoneNumber           string  `json:"phoneNumber"`
	Address               *string `json:"address,omitempty"`
	DateOfBirth           int     `json:"dateOfBirth"`
	Gender                string  `json:"gender"`
	ProfilePicture        *string `json:"profilePicture,omitempty"`
}

type Prescription struct {
	PrescriptionID int                 `json:"prescriptionID"`
	VisitID        int                 `json:"visitID"`
	CreatedAt      int                 `json:"createdAt"`
	Items          []*PrescriptionItem `json:"items"`
	Instructions   *string             `json:"instructions,omitempty"`
}

type PrescriptionInput struct {
	VisitID      int                      `json:"visitID"`
	Instructions *string                  `json:"instructions,omitempty"`
	Items        []*PrescriptionItemInput `json:"items"`
}

type PrescriptionItem struct {
	ID             int    `json:"id"`
	MedicationName string `json:"medicationName"`
	Dosage         string `json:"dosage"`
	Frequency      string `json:"frequency"`
	Duration       *int   `json:"duration,omitempty"`
}

type PrescriptionItemInput struct {
	ID        int    `json:"id"`
	Frequency string `json:"frequency"`
	Duration  int    `json:"duration"`
}

type Query struct {
}

type User struct {
	UserID         int     `json:"userID"`
	Username       string  `json:"username"`
	Password       string  `json:"password"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	Role           string  `json:"role"`
	Address        *string `json:"address,omitempty"`
	DateOfBirth    *int    `json:"dateOfBirth,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	DateJoined     int     `json:"dateJoined"`
	LastLogin      *int    `json:"lastLogin,omitempty"`
	Status         string  `json:"status"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
	CreatedAt      int     `json:"createdAt"`
	UpdatedAt      int     `json:"updatedAt"`
}

type UserInput struct {
	Username       string  `json:"username"`
	Password       string  `json:"password"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	PhoneNumber    *string `json:"phoneNumber,omitempty"`
	Role           string  `json:"role"`
	Address        *string `json:"address,omitempty"`
	DateOfBirth    *int    `json:"dateOfBirth,omitempty"`
	Gender         *string `json:"gender,omitempty"`
	DateJoined     int     `json:"dateJoined"`
	LastLogin      *int    `json:"lastLogin,omitempty"`
	Status         string  `json:"status"`
	ProfilePicture *string `json:"profilePicture,omitempty"`
}

type Visit struct {
	VisitID           int           `json:"visitID"`
	PatientID         int           `json:"patientID"`
	PrescriptionID    *int          `json:"prescriptionID,omitempty"`
	Details           *string       `json:"details,omitempty"`
	Diagnosis         *string       `json:"diagnosis,omitempty"`
	Notes             *string       `json:"notes,omitempty"`
	VisitDate         int           `json:"visitDate"`
	VisitPrescription *Prescription `json:"visit_prescription,omitempty"`
}

type VisitInput struct {
	PatientID      int     `json:"patientID"`
	PrescriptionID *int    `json:"prescriptionID,omitempty"`
	Details        *string `json:"details,omitempty"`
	Diagnosis      *string `json:"diagnosis,omitempty"`
	Notes          *string `json:"notes,omitempty"`
	VisitDate      int     `json:"visitDate"`
}
